steps:
 - task: AzureResourceGroupDeployment@2
   displayName: Application Insights - ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/ApplicationInsights/deploy.json'
     overrideParameters: '-webappappinsightname "${{ parameters.webappappinsightname }}" -webjobappinsightname "${{ parameters.webjobappinsightname }}"'
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to Application Insights webappappinsightname
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.webappappinsightname }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Application Insights webjobappinsightname
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.webjobappinsightname }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Set Build Variable From ARM Output
   name: SetApplicationInsightsOutputVariable
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Set-OutputVariable.ps1'
     ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}"'
     azurePowerShellVersion: LatestVersion