steps:
 - script: 'echo Service Plan SKU - ${{ parameters.appServicePlanSku }}'
 - task: AzureResourceGroupDeployment@2
   displayName: App Service Plan - ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/App ServicePlan/deploy.json'
     overrideParameters: '-appServicePlanName "${{ parameters.appServicePlanName }}" -location "${{ parameters.deployLocation }}"  -appServicePlanSku "${{ parameters.appServicePlanSku }}"'
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to App Service Plan
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.appServicePlanName }}"'
     azurePowerShellVersion: LatestVersion