steps:
 - task: AzureResourceGroupDeployment@2
   displayName: Azure Cache for Redis - ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/Azure Cache for Redis/deploy.json'
     overrideParameters: '-redisName "${{ parameters.redisName }}" -redisSkuName "${{ parameters.redisSkuName }}" -redisSkuFamily "${{ parameters.redisSkuFamily }}" -redisSkuCapacity "${{ parameters.redisSkuCapacity }}" -location "${{ parameters.deployLocation }}" -redisMaxMemoryReserved "${{ parameters.redisMaxMemoryReserved }}" -redisMaxMemoryPolicy "${{ parameters.redisMaxMemoryPolicy }}" -redisMaxFragmentationMemory "${{ parameters.redisMaxFragmentationMemory }}" -redisMaxMemoryDelta "${{ parameters.redisMaxMemoryDelta }}" -redisMaxclients "${{ parameters.redisMaxclients }}"'
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to Azure Cache for Redis
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.redisName }}"'
     azurePowerShellVersion: LatestVersion

#  - task: AzurePowerShell@4
#    displayName: Set Build Variable From ARM Output
#    name: SetRedisOutputVariable
#    inputs:
#      azureSubscription: "${{ parameters.azureSubscriptionName }}"
#      ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Set-OutputVariable.ps1'
#      ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}"'
#      azurePowerShellVersion: LatestVersion

