steps:
 - task: AzureResourceGroupDeployment@2
   displayName: Search Service - ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/Search Service/deploy.json'
     overrideParameters: '-searchServiceName "${{ parameters.searchServiceName }}" -location "${{ parameters.deployLocation }}" -searchServicesSku "${{ parameters.searchServicesSku }}" -searchServicesReplicaCount "${{ parameters.searchServicesReplicaCount }}" -searchServicesPartitionCount "${{ parameters.searchServicesPartitionCount }}"'
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to Search Service
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.searchServiceName }}"'
     azurePowerShellVersion: LatestVersion

#  - task: AzurePowerShell@4
#    displayName: Set Build Variable From ARM Output
#    name: SetSearchServiceOutputVariable
#    inputs:
#      azureSubscription: "${{ parameters.azureSubscriptionName }}"
#      ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Set-OutputVariable.ps1'
#      ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}"'
#      azurePowerShellVersion: LatestVersion