steps:
 - task: AzureResourceGroupDeployment@2
   displayName: Storage Account With Configuration Hot fix ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/Storage Account Configuration/deploy.json'
     overrideParameters: '-storageAccountType "${{ parameters.storageAccountType }}" -storageAccounts_storage_name "${{ parameters.storageAccountName }}"'
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to Storage Account With Configuration Hot fix
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.storageAccountName }}"'
     azurePowerShellVersion: LatestVersion
