steps:
 - task: AzureResourceGroupDeployment@2
   displayName: Web API - ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/Web API/template.json'
     overrideParameters: '-rolesApi ${{ parameters.rolesApi }} -remoteApi ${{ parameters.remoteApi }} -rdbgApi ${{ parameters.rdbgApi }} -widgetApi ${{ parameters.widgetApi }} -riskRepoApi ${{ parameters.riskRepoApi }} -devopsProfileApi ${{ parameters.devopsProfileApi }} -nspApi ${{ parameters.nspApi }}  -cpoeApi ${{ parameters.cpoeApi }}  -metricDataIngestionClientapi ${{ parameters.metricDataIngestionClientapi }}  -acrApi ${{ parameters.acrApi }} -envApi ${{ parameters.envApi }} -apiAppServicePlanName "${{ parameters.apiAppServicePlanName }}" -apiAppServicePlanSku "${{ parameters.apiAppServicePlanSku }}"'
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - rolesApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.rolesApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - remoteApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.remoteApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - rdbgApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.rdbgApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - widgetApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.widgetApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - riskRepoApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.riskRepoApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - devopsProfileApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.devopsProfileApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - nspApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.nspApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - cpoeApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.cpoeApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - metricDataIngestionClientapi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.metricDataIngestionClientapi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - acrApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.acrApi }}"'
     azurePowerShellVersion: LatestVersion

 - task: AzurePowerShell@4
   displayName: Add tags to Web API - envApi
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.envApi }}"'
     azurePowerShellVersion: LatestVersion

#  - task: AzurePowerShell@4
#    displayName: Set Build Variable From ARM Output
#    name: SetWebApiOutputVariable
#    inputs:
#      azureSubscription: "${{ parameters.azureSubscriptionName }}"
#      ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Set-OutputVariable.ps1'
#      ScriptArguments: '-resourceGroupName "${{ parameters.resourceGroupName }}"'
#      azurePowerShellVersion: LatestVersion