steps:
 - script: 'echo ${{ parameters.webjob_name }} ${{ parameters.webjobserverfarm_name }}'
 - task: AzureResourceGroupDeployment@2
   displayName: Web Job - ARM
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     resourceGroupName: "${{ parameters.resourceGroupName }}"
     location: "${{ parameters.deployLocation }}"
     csmFile: '$(Agent.BuildDirectory)/Drop/Templates/Web Job/deploy.json'
     overrideParameters: '-webjob_name "${{ parameters.webjob_name }}" -location "${{ parameters.deployLocation }}" -webjobserverfarm_name "${{ parameters.webjobserverfarm_name }}"'
     deploymentOutputs: armOut

 - task: AzurePowerShell@4
   displayName: Add tags to Web Job
   inputs:
     azureSubscription: "${{ parameters.azureSubscriptionName }}"
     ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/Add-Tags.ps1'
     ScriptArguments: '-resourceType "Primary" -resourcePurpose "" -componentID "${{ parameters.componentID }}" -subEnvironment "${{ parameters.subEnvironment }}" -resourceGroupName "${{ parameters.resourceGroupName }}" -resourceName "${{ parameters.webjob_name }}"'
     azurePowerShellVersion: LatestVersion