jobs:
  - deployment: Deploy_DevOpsProfileApi
    pool:
     name: 'virtuosoinfra1'
    environment: ${{parameters.env}}
    strategy:
      runOnce:
        deploy:
          steps:

          - script: echo '##vso[task.setvariable variable=env]${{parameters.env}}
            displayName: 'Set Environment Variable'

          - powershell: |
              $date=$(Get-Date -Format g);
              Write-Host "##vso[task.setvariable variable=creationDate]$date"
            displayName: 'Set Date Tag'

          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: DropAppArtifacts
              downloadPath: '$(System.ArtifactsDirectory)'
              buildType: 'current'
              downloadType: 'single'                      
           
          - task: AzureRmWebAppDeployment@4
            displayName: 'Azure App Service Deploy: virtuosotestdevopsprofileapi'
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              WebAppName: virtuosotestdevopsprofileapi
              packageForLinux: '$(System.ArtifactsDirectory)/DropAppArtifacts/devopsapi'
              enableCustomDeployment: true
              RemoveAdditionalFilesFlag: true
              RenameFilesFlag: false