jobs:
  - deployment: Deploy_WebJobs
    pool:
     name: 'virtuosoinfra1'
    environment: ${{parameters.env}}
    strategy:
      runOnce:
        deploy:
          steps:

          - script: echo '##vso[task.setvariable variable=env]${{parameters.env}}
            displayName: 'Set Environment Variable'

          - powershell: |
              $date=$(Get-Date -Format g);
              Write-Host "##vso[task.setvariable variable=creationDate]$date"
            displayName: 'Set Date Tag'

          - task: DownloadBuildArtifacts@0
            displayName: 'Download Build Artifacts'
            inputs:
              artifactName: DropAppArtifacts
              downloadPath: '$(System.ArtifactsDirectory)'
              buildType: 'current'
              downloadType: 'single'                      
           
          - task: AzurePowerShell@2
            displayName: DevOpsMaturityDataProcessor
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/cronwebjob.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\DevOpsMaturityDataProcessor\DevOpsMaturityDataProcessor.zip" -jobname "DevOpsMaturityDataProcessortest" -WebsiteName "$(webjob_name)" -jobtype "Triggered" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: DevOpsMaturityProjectDataProcessor
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/continuous.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\DevOpsMaturityProjectDataProcessor\DevOpsMaturityProjectDataProcessor.zip" -jobname "DevOpsMaturityProjectDataProcessor" -WebsiteName "$(webjob_name)" -jobtype "continuous" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: SlowBurnSyncJob
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/cronwebjob.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\SlowBurnSyncJob\SlowBurnSyncJob.zip" -jobname "NWSRiskLeakageSyncJob" -WebsiteName "$(webjob_name)" -jobtype "Triggered" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: CosmicCaseManager
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/cronwebjob.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\CosmicCaseManager\CosmicCaseManager.zip" -jobname "CosmicCaseManagertest" -WebsiteName "$(webjob_name)" -jobtype "Triggered" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: ProjectOnline
            inputs:
               azureSubscription: VWW-DEV-Subscription-Service-Connection
               ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/continuous.ps1'
               ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\projectonline\ProjectOnline\ProjectOnline.zip" -jobname "ProjectOnlinetest" -WebsiteName "$(webjob_name)" -jobtype "continuous" -rgname "$(resourceGroupApp)"'
               azurePowerShellVersion: LatestVersion
               continueOnError: true
               condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: ChangePointDataProcessor
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/continuous.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\ChangePointDataProcessor\ChangePointDataProcessor.zip" -jobname "ChangePointDataProcessor" -WebsiteName "$(webjob_name)" -jobtype "continuous" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: PhoenixCatalogSync
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/cronwebjob.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\PhoenixCatalogSync\PhoenixCatalogSync.zip" -jobname "PhoenixCatalogSync" -WebsiteName "$(webjob_name)" -jobtype "Triggered" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: MobileNotificationUpdate
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/continuous.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\MobileNotificationUpdate\MobileNotificationUpdate.zip" -jobname "MobileNotificationUpdate" -WebsiteName "$(webjob_name)" -jobtype "continuous" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: PIHCalculator
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/continuous.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\PIHCalculator\PIHCalculator.zip" -jobname "PIHCalculator" -WebsiteName "$(webjob_name)" -jobtype "continuous" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
          - task: AzurePowerShell@2
            displayName: Rbdg
            inputs:
              azureSubscription: VWW-DEV-Subscription-Service-Connection
              ScriptPath: '$(Agent.BuildDirectory)/Drop/Scripts/continuous.ps1'
              ScriptArguments: '-Zipfilelocation "$(System.ArtifactsDirectory)\DropAppArtifacts\rdbgwebjob\rdbgwebjob.zip" -jobname "rdbgwebjobTest" -WebsiteName "$(rdbgApi)" -jobtype "continuous" -rgname "$(resourceGroupApp)"'
              azurePowerShellVersion: LatestVersion
            continueOnError: true
            condition: succeededOrFailed()
 