variables:
  - template: /Pipelines/Templates/Variables/package.yml
  - template: /Pipelines/Templates/Variables/tags.yml
  - template: /Pipelines/Templates/Variables/infra.yml

trigger: none
pr: none

stages:  
  - stage: Startup
    jobs:
    - job: Initialize 
      pool:
        name: "virtuosoinfra1"
      steps:
      - script: echo 'Initialisation completed'
        
  - stage: Build_Infra_Artifacts
    jobs:
      - template: /Pipelines/Templates/Stage/infra.build.yml
    dependsOn:
    - Startup
    condition: succeeded('Startup')     

  - stage: Download_App_Artifacts
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/apps.download.yml

    dependsOn:
    - Startup
    condition: succeeded('Startup') 

  - stage: Deploy_Test_Infra
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/infra.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Build_Infra_Artifacts
    - Download_App_Artifacts
    condition: and(succeeded('Build_Infra_Artifacts'), succeeded('Download_App_Artifacts')) 
    

  - stage: Deploy_Test_Apps
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/apps.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Infra
    condition: succeeded('Deploy_Test_Infra')

  - stage: Deploy_Test_DevOpsProfileApi
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/devopsprofileapi.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Infra
    condition: succeeded('Deploy_Test_Infra')

  - stage: Deploy_Test_WebJobs_Phase1
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/webjobs1.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps')

  - stage: Deploy_Test_WebJobs_Phase2
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/webjobs2.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps')

  - stage: Deploy_Test_WebJobs_Phase3
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/webjobs3.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps')

  - stage: Deploy_Test_SQL
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/sqldacpac.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps')

  - stage: Deploy_Test_WebJobs_Phase4
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/webjobs4.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps')

  - stage: Deploy_Test_WebJobs_Phase5
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/webjobs5.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps')

  - stage: Deploy_Test_WebJobs_Phase6
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/webjobs6.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps')

  - stage: Deploy_Test_Metric_Framework
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/metricframework.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps')

  - stage: Deploy_Test_Function_Apps
    variables:
      - group: vwwtest
      - template: /Pipelines/Templates/Variables/test.yml
    jobs:
      - template: /Pipelines/Templates/Stage/functionapps.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Apps
    condition: succeeded('Deploy_Test_Apps') 

  - stage: Deploy_Staging
    variables:
      - group: vwwstaging
      - template: /Pipelines/Templates/Variables/staging.yml
    jobs:
      - template: /Pipelines/Templates/Stage/infra.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Test_Function_Apps
    condition: succeeded(' Deploy_Test_Function_Apps') 

  - stage: Deploy_Demo
    variables:
      - group: vwwdemo
      - template: /Pipelines/Templates/Variables/demo.yml
    jobs:
      - template: /Pipelines/Templates/Stage/infra.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
    - Deploy_Staging
    condition: succeeded('Deploy_Staging')

  - stage: Deploy_Prod
    variables:
      - group: vwwprod
      - template: /Pipelines/Templates/Variables/prod.yml
    jobs:
      - template: /Pipelines/Templates/Stage/infra.deploy.yml
        parameters:
          env: ${{ variables.env }}
          serviceConnection: ${{ variables.serviceConnection }}
    dependsOn:
        - Deploy_Demo
    condition: succeeded('Deploy_Demo') 