variables:
- name: storageAccountKind
  value: 'Premium_LRS'
- name: serviceConnection
  value: 'VWW-DEV-Subscription-Service-Connection'
- name: env
  value: 'prod'
- name: region
  value: 'East US'
- name: regionShortName
  value: 'eus'
- name: regionlocation
  value: 'eastus'
- name: keyVaultSku
  value: 'Premium'
- name: redisSkuName
  value: 'Premium'
- name: redisSkuFamily
  value: 'P'
- name: redisSkuCapacity
  value: 2
- name: redisMaxclients
  value: "15000"
- name: redisMaxMemoryReserved
  value: "200"
- name: redisMaxMemoryPolicy
  value: "volatile-lru"
- name: redisMaxFragmentationMemory
  value: "0"
- name: redisMaxMemoryDelta
  value: "200"
- name: dataExplorerClusterSkuName
  value: "Standard_D13_v2"
- name: dataExplorerClusterSkuTier
  value: "Standard"
- name: dataExplorerClusterSkuCapacity
  value: "6"
- name: searchServicesSku
  value: "basic"
- name: searchServicesReplicaCount
  value: "1"
- name: searchServicesPartitionCount
  value: "1"
- name: serviceBusSku
  value: 'Premium'
- name: appServicePlanSku
  value: 'P1'
- name: apiAppServicePlanSku
  value: 'P1'
- name: sqlElasticPoolEdition
  value: 'Premium'
- name: sqlElasticPoolCapacity
  value: 125
- name: sqlDbSkuTier
  value: "Premium"
- name: funcspsku
  value: 'P1'